spring:
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
  datasource:
    url: jdbc:mariadb://localhost:3306/minicampus
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: zerobase
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: lms.testing.02@gmail.com
    password: aaavellrcbodimei
    properties:
      mail:
        smtp:
          starttls:
            enable: true




